### ISSUE TITLE
where is Y.php ?

### ISSUE THREAD

**Issue by cornernote** [mirkhamidov/yii2-shortcuts#1]
seems to not have the class, and the require in composer points to Yii1 shortcuts class

**Comment by mirkhamidov** [comment]
its not finished (

**Comment by cornernote** [comment]
I ended up making my own, perhaps we can work on it together?

https://github.com/cornernote/yii2-shortcuts

**Comment by mirkhamidov** [comment]
Its a good idea))
you can write me to mirkhamidov[dot]jasur[at]gmail[dot]com
